### PR TITLE
patches: Remove UnwindRegistersSave.S patch

### LINKED ISSUE #4: Change to UnwindRegistersSave.s?
Can someone please explain why this patch is applied - https://github.com/unikraft/lib-libunwind/blob/staging/patches/0001-Updated-the-RIP.patch

It seems to break exceptions and cause an access 0x0 due to this instruction - `movq %rbp, (%rax)`. I ran the helloworld-cpp template with exceptions and it gave an error. I am not sure I understand the exception handling implementation in unikraft, because even when I am handling an error it says exited with uncaught exception.

### PR DESCRIPTION
**Pull request by eduardvintila**
As [pointed out](https://github.com/unikraft/lib-libunwind/pull/5#issuecomment-1524915146) by @mschlumpp, the `UnwindRegistersSave.S` patch is no longer relevant since it incorrectly saved the RIP from the frame of the function which caused the exception. This PR simply removes this problematic patch altogether.

GitHub-Fixes: https://github.com/unikraft/lib-libunwind/issues/4
Signed-off-by: Eduard Vintilă <eduard.vintila47@gmail.com>

### CODE REVIEW

**Comment by jschlumpp** [comment]
Why does this patch even exist? The resulting code seems to save the registers of the previous frame but saves the PC of the one before that. That seems very broken to me.

**Comment by eduardvintila** [comment]
@mschlumpp, you make a good point. I've modified the PR to just completely remove this problematic patch.

**Review by mogasergiu — COMMENTED** [review]
Maybe @vladandrew could tell us if he remembers what this patch was for before removing it entirely? Since he is the author and committer maybe he did have a reason back then that we are not seeing, due to lack of context. It would also be helpful to have it in the conversation history of the removal of this patch.

But yeah, I agree, that register dereference is faulty nevertheless.

**Comment by eduardvintila** [comment]
@mogasergiu @mschlumpp , yes, completely agree that this shouldn't be merged without an input from @vladandrew. However,  @razvand talked with him yesterday about this and said that it was mostly a workaround for a bug at the time in Unikraft and that it should be deleted. Indeed, it would also be great to have it in the conversation history here, as well.

**Review by mogasergiu — APPROVED** [review]
Ok, got it.

Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

**Review by jschlumpp — APPROVED** [review]
Reviewed-by: Marco Schlumpp <marco@unikraft.io>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
