### PR TITLE
Fix unwinding

### PR DESCRIPTION
**Pull request by jschlumpp**
libunwind has to unwind its own functions too when unwinding the complete stack. Without unwind tables this is impossible. Therefore, enable them for libunwind itself. Also remove the patch which just skipped those internal libunwind functions to work-around the missing unwind tables. This work-around caused a mismatch between the actual stack state and what the unwind tables of the user application expected.

### CODE REVIEW

**Comment by jviotti** [comment]
Thanks for the quick fix @mschlumpp . I confirm it works on Debian Bookworm!

**Comment by jviotti** [comment]
Is there anything pending before we can merge this? Would love to use it already, without having to point to the fork

**Review by StefanJum — CHANGES_REQUESTED** [review]
This works fine @mschlumpp, thanks.

Please author the commit using the same email address that you use for the SOB (it's authored by `<marco.schlumpp@gmail.com>` now).
I would also add a bit more descriptive commit message, `Fix unwinding` is too general.

**Review by StefanJum — APPROVED** [review]
All good now, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by mariasfiraiala — APPROVED** [review]
It's the second time we are removing this patch, hopefully this time for good! The changes are alright, thanks @mschlumpp!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Comment by jviotti** [comment]
Not that it needs to happen right now, but out of curiosity, how do changes to `staging` eventually migrate to the `stable` branch? What is the process?

**Comment by razvand** [comment]
> Not that it needs to happen right now, but out of curiosity, how do changes to `staging` eventually migrate to the `stable` branch? What is the process?

@jviotti , currently, when we do a release we switch things to stable, once we have tested everything. The goal would be that, in the not-so-far term, we would be able to have an automated transition of `staging` to stable, once we test everything.

In case of certain commits / PRs, we can do manual testing and then make their transition to `stable`. If you want that to happen to this PR, we can do it.

**Comment by jviotti** [comment]
Makes sense!

> In case of certain commits / PRs, we can do manual testing and then make their transition to stable. If you want that to happen to this PR, we can do it.

No worries, `staging` is fine. I was just wondering what the process was

**Pull request merged**
